// Package bff provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bff

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for MfaVerificationMethod.
const (
	MfaVerificationMethodRecoveryCode MfaVerificationMethod = "recovery_code"
	MfaVerificationMethodTotp         MfaVerificationMethod = "totp"
)

// Valid indicates whether the value is a known member of the MfaVerificationMethod enum.
func (e MfaVerificationMethod) Valid() bool {
	switch e {
	case MfaVerificationMethodRecoveryCode:
		return true
	case MfaVerificationMethodTotp:
		return true
	default:
		return false
	}
}

// Defines values for TotpEnrollmentRequestMethod.
const (
	TotpEnrollmentRequestMethodRecoveryCode TotpEnrollmentRequestMethod = "recovery_code"
	TotpEnrollmentRequestMethodTotp         TotpEnrollmentRequestMethod = "totp"
)

// Valid indicates whether the value is a known member of the TotpEnrollmentRequestMethod enum.
func (e TotpEnrollmentRequestMethod) Valid() bool {
	switch e {
	case TotpEnrollmentRequestMethodRecoveryCode:
		return true
	case TotpEnrollmentRequestMethodTotp:
		return true
	default:
		return false
	}
}

// CurrentOperator De quoi nommer l'opérateur à l'écran, et rien de plus. Ni `password_hash`, ni
// `mfa_totp_secret`, ni les identifiants WebAuthn : le type de domaine du store ne traverse pas
// cette frontière (§1.11), et `additionalProperties: false` fait refuser tout champ qu'un
// serveur ajouterait par mégarde.
type CurrentOperator struct {
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	Id          string `json:"id"`
}

// Error La forme d'erreur unique du produit. `code` se grep dans les journaux et ne se traduit pas,
// `message` s'affiche à l'opérateur. Le champ `errors[]` que le §1.4 annonce arrive avec la
// première route qui relaie la passerelle (step-060).
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health Réponse de la sonde de vivacité.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest Le premier facteur, tel que le formulaire de connexion l'envoie.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me Ce qu'une session vivante apprend au client.
type Me struct {
	AbsoluteExpiresAt time.Time `json:"absoluteExpiresAt"`
	Elevated          bool      `json:"elevated"`

	// Operator De quoi nommer l'opérateur à l'écran, et rien de plus. Ni `password_hash`, ni
	// `mfa_totp_secret`, ni les identifiants WebAuthn : le type de domaine du store ne traverse pas
	// cette frontière (§1.11), et `additionalProperties: false` fait refuser tout champ qu'un
	// serveur ajouterait par mégarde.
	Operator    CurrentOperator `json:"operator"`
	Permissions []string        `json:"permissions"`

	// SecondFactors Ce que l'opérateur détient comme second facteur — jamais ce qu'il vaut. Un booléen et un
	// compte ne se rejouent pas, là où le secret et les codes eux-mêmes ne sont montrés qu'une fois,
	// à l'enrôlement.
	//
	// C'est ce qui permet à l'écran de savoir s'il conduit à l'enrôlement ou au challenge, sans
	// essayer l'un pour découvrir qu'il fallait l'autre. step-024 y ajoutera le compte de passkeys.
	SecondFactors SecondFactors `json:"secondFactors"`
}

// MfaChallenge Le challenge de second facteur. C'est un objet en base et non un jeton signé : il doit être
// révocable à la seconde où il est consommé, ce qu'un jeton sans état ne permet pas. Le serveur
// n'en garde que l'empreinte — cette valeur n'est rendue qu'une fois.
type MfaChallenge struct {
	Challenge string    `json:"challenge"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// MfaVerification Ce que le formulaire du second facteur envoie. Le challenge vient de la réponse à
// `POST /auth/login` ; le cookie de session, lui, voyage tout seul.
type MfaVerification struct {
	Challenge string                `json:"challenge"`
	Code      string                `json:"code"`
	Method    MfaVerificationMethod `json:"method"`
}

// MfaVerificationMethod defines model for MfaVerification.Method.
type MfaVerificationMethod string

// SecondFactors Ce que l'opérateur détient comme second facteur — jamais ce qu'il vaut. Un booléen et un
// compte ne se rejouent pas, là où le secret et les codes eux-mêmes ne sont montrés qu'une fois,
// à l'enrôlement.
//
// C'est ce qui permet à l'écran de savoir s'il conduit à l'enrôlement ou au challenge, sans
// essayer l'un pour découvrir qu'il fallait l'autre. step-024 y ajoutera le compte de passkeys.
type SecondFactors struct {
	RecoveryCodesRemaining int  `json:"recoveryCodesRemaining"`
	Totp                   bool `json:"totp"`
}

// TotpEnrollment Rendu **une seule fois**, à l'enrôlement. Aucune route ne le rend ensuite : le secret est
// chiffré au repos et les codes sont hachés, donc le serveur lui-même ne saurait plus les
// recomposer.
type TotpEnrollment struct {
	OtpauthUri    string   `json:"otpauthUri"`
	RecoveryCodes []string `json:"recoveryCodes"`
	Secret        string   `json:"secret"`
}

// TotpEnrollmentRequest Ce qu'un enrôlement présente : **rien** la première fois, et une preuve du facteur en place
// pour le remplacer.
//
// Le premier enrôlement n'a rien à prouver — il n'y a pas encore de facteur, et la session de
// premier facteur dit déjà de qui il s'agit. Le remplacement, lui, **détruit** l'authentificateur
// en place et ses dix codes de récupération : il exige donc de présenter ce qu'on détruit.
//
// **Pourquoi un code et non un challenge frais**, alors que le challenge est ce que la
// vérification exige : se reconnecter pour en obtenir un ferme la session présentée et la
// désélève — c'est la remédiation de step-022 — donc un remplacement exigeant à la fois
// l'élévation et un challenge frais serait **inatteignable**. Mesuré : le scénario qui l'exerçait
// rendait 409 en boucle. Un code du facteur en place est par ailleurs une preuve plus forte que
// le mot de passe : un cookie de session élevée capté ne le donne pas.
//
// Un code de récupération convient aussi. L'opérateur qui a perdu son téléphone est précisément
// celui qui veut réenrôler, et n'exiger qu'un code TOTP en ferait une impasse.
type TotpEnrollmentRequest struct {
	Code   *string                      `json:"code,omitempty"`
	Method *TotpEnrollmentRequestMethod `json:"method,omitempty"`
}

// TotpEnrollmentRequestMethod defines model for TotpEnrollmentRequest.Method.
type TotpEnrollmentRequestMethod string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// EnrollTotpJSONRequestBody defines body for EnrollTotp for application/json ContentType.
type EnrollTotpJSONRequestBody = TotpEnrollmentRequest

// VerifyMfaJSONRequestBody defines body for VerifyMfa for application/json ContentType.
type VerifyMfaJSONRequestBody = MfaVerification

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Premier facteur — adresse et mot de passe
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Fermer la session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Me L'opérateur connecté et ce qu'il a le droit de faire
	// (GET /auth/me)
	Me(w http.ResponseWriter, r *http.Request)
	// EnrollTotp Enrôler une application d'authentification
	// (POST /auth/mfa/totp/enroll)
	EnrollTotp(w http.ResponseWriter, r *http.Request)
	// VerifyMfa Second facteur — code TOTP ou code de récupération
	// (POST /auth/mfa/verify)
	VerifyMfa(w http.ResponseWriter, r *http.Request)
	// Health Sonde de vivacité
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login Premier facteur — adresse et mot de passe
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Fermer la session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Me L'opérateur connecté et ce qu'il a le droit de faire
// (GET /auth/me)
func (_ Unimplemented) Me(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// EnrollTotp Enrôler une application d'authentification
// (POST /auth/mfa/totp/enroll)
func (_ Unimplemented) EnrollTotp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyMfa Second facteur — code TOTP ou code de récupération
// (POST /auth/mfa/verify)
func (_ Unimplemented) VerifyMfa(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Sonde de vivacité
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Me(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollTotp operation middleware
func (siw *ServerInterfaceWrapper) EnrollTotp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollTotp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyMfa operation middleware
func (siw *ServerInterfaceWrapper) VerifyMfa(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyMfa(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.Me)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/mfa/totp/enroll", wrapper.EnrollTotp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/mfa/verify", wrapper.VerifyMfa)
	})

	return r
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse MfaChallenge

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse Error

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ResponseHeaders struct {
	RetryAfter int
}

type Login429JSONResponse struct {
	Body    Error
	Headers Login429ResponseHeaders
}

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type MeRequestObject struct {
}

type MeResponseObject interface {
	VisitMeResponse(w http.ResponseWriter) error
}

type Me200JSONResponse Me

func (response Me200JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Me401JSONResponse Error

func (response Me401JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollTotpRequestObject struct {
	Body *EnrollTotpJSONRequestBody
}

type EnrollTotpResponseObject interface {
	VisitEnrollTotpResponse(w http.ResponseWriter) error
}

type EnrollTotp200JSONResponse TotpEnrollment

func (response EnrollTotp200JSONResponse) VisitEnrollTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollTotp400JSONResponse Error

func (response EnrollTotp400JSONResponse) VisitEnrollTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollTotp401JSONResponse Error

func (response EnrollTotp401JSONResponse) VisitEnrollTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EnrollTotp409JSONResponse Error

func (response EnrollTotp409JSONResponse) VisitEnrollTotpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMfaRequestObject struct {
	Body *VerifyMfaJSONRequestBody
}

type VerifyMfaResponseObject interface {
	VisitVerifyMfaResponse(w http.ResponseWriter) error
}

type VerifyMfa204Response struct {
}

func (response VerifyMfa204Response) VisitVerifyMfaResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type VerifyMfa400JSONResponse Error

func (response VerifyMfa400JSONResponse) VisitVerifyMfaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMfa401JSONResponse Error

func (response VerifyMfa401JSONResponse) VisitVerifyMfaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyMfa429ResponseHeaders struct {
	RetryAfter int
}

type VerifyMfa429JSONResponse struct {
	Body    Error
	Headers VerifyMfa429ResponseHeaders
}

func (response VerifyMfa429JSONResponse) VisitVerifyMfaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse Health

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Premier facteur — adresse et mot de passe
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Fermer la session
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Me L'opérateur connecté et ce qu'il a le droit de faire
	// (GET /auth/me)
	Me(ctx context.Context, request MeRequestObject) (MeResponseObject, error)
	// EnrollTotp Enrôler une application d'authentification
	// (POST /auth/mfa/totp/enroll)
	EnrollTotp(ctx context.Context, request EnrollTotpRequestObject) (EnrollTotpResponseObject, error)
	// VerifyMfa Second facteur — code TOTP ou code de récupération
	// (POST /auth/mfa/verify)
	VerifyMfa(ctx context.Context, request VerifyMfaRequestObject) (VerifyMfaResponseObject, error)
	// Health Sonde de vivacité
	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Me operation middleware
func (sh *strictHandler) Me(w http.ResponseWriter, r *http.Request) {
	var request MeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Me(ctx, request.(MeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Me")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MeResponseObject); ok {
		if err := validResponse.VisitMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EnrollTotp operation middleware
func (sh *strictHandler) EnrollTotp(w http.ResponseWriter, r *http.Request) {
	var request EnrollTotpRequestObject

	var body EnrollTotpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EnrollTotp(ctx, request.(EnrollTotpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrollTotp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EnrollTotpResponseObject); ok {
		if err := validResponse.VisitEnrollTotpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyMfa operation middleware
func (sh *strictHandler) VerifyMfa(w http.ResponseWriter, r *http.Request) {
	var request VerifyMfaRequestObject

	var body VerifyMfaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyMfa(ctx, request.(VerifyMfaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyMfa")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyMfaResponseObject); ok {
		if err := validResponse.VisitVerifyMfaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
