/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonde de vivacité
         * @description Répond « le process est en vie », pas « le service est disponible ». Ne touche ni la base ni
         *     la passerelle : y brancher une dépendance ferait redémarrer un serveur sain parce qu'une
         *     autre brique est tombée. La sonde de disponibilité arrive en step-186.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Premier facteur — adresse et mot de passe
         * @description Vérifie l'adresse et le mot de passe, ouvre une session de **premier facteur** et rend un
         *     **challenge de second facteur** à usage unique et de courte durée. La session n'est pas
         *     élevée : c'est step-023 et step-024 qui vérifieront ce second facteur.
         *
         *     Le cookie de session n'est pas déclaré ici, et c'est délibéré : il est `HttpOnly`, donc le
         *     navigateur **interdit** au client de le lire. Le déclarer en en-tête de réponse le ferait
         *     apparaître dans les types engendrés comme une valeur lisible, ce qu'il n'est pas.
         *
         *     Le refus ne dit jamais lequel des deux facteurs a échoué. Même code, même corps et **même
         *     durée** pour « adresse inconnue », « mot de passe faux » et « compte désactivé » : les
         *     distinguer dirait à une machine quelles adresses existent.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'opérateur connecté et ce qu'il a le droit de faire
         * @description Le **seul** endroit d'où le client apprend ses droits. L'interface se rend sur des
         *     permissions, jamais sur un rôle codé en dur (§4.2).
         *
         *     Aucun rôle dans le corps, et c'est la raison même : une liste de rôles rendue au navigateur
         *     invite à réintroduire le contrôle de rôle côté client, que la spec interdit. Les permissions
         *     décident ; les rôles restent au serveur tant qu'aucun écran n'a besoin de les afficher.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fermer la session
         * @description La ligne de session est **supprimée**, et le cookie expiré. Le second sans le premier ne
         *     protège rien : un cookie qu'on garde se rejoue.
         *
         *     **Le même statut sans session**, et c'est délibéré : se déconnecter est une demande d'état,
         *     et l'état est atteint. Un refus obligerait le client à traiter un cas sans conséquence, et
         *     dirait à qui teste un cookie s'il vaut encore quelque chose. C'est aussi le moment où
         *     l'opérateur veut le plus que ce bouton marche — sur une session déjà morte.
         *
         *     Aucun corps : rien à dire que le statut ne dise. Le cookie d'expiration n'est pas déclaré
         *     ici, pour la même raison qu'à la connexion — il est `HttpOnly`, le client ne le lit pas.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/totp/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrôler une application d'authentification
         * @description Tire un secret TOTP, le chiffre au repos, et rend **une seule fois** de quoi le configurer :
         *     l'URI `otpauth://` que l'écran dessinera en QR, le secret en clair pour la saisie manuelle, et
         *     dix codes de récupération. Rien de tout cela n'est réaffichable ensuite — aucune action
         *     « révéler » n'existe, et la seule sortie est un réenrôlement.
         *
         *     Le serveur rend l'**URI** et non une image : dessiner le QR appartient au client (step-028), et
         *     l'inverse ferait dépendre le serveur d'une bibliothèque de rendu.
         *
         *     L'enrôlement n'élève pas la session : c'est `POST /auth/mfa/verify` qui le fait, avec le
         *     premier code. Tant qu'il n'a pas eu lieu, la session reste au premier facteur.
         *
         *     **Deux chemins d'enrôlement et non un seul**, contrairement à ce que le §5.1 annonçait : la
         *     cérémonie WebAuthn de step-024 rendra une forme entièrement différente, et les réunir sous une
         *     opération obligerait à un `oneOf` de réponse dont le code engendré fait un type opaque. La
         *     vérification, elle, rend le même 204 des deux côtés et reste une seule opération.
         */
        post: operations["enrollTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Second facteur — code TOTP ou code de récupération
         * @description Vérifie le second facteur et **élève** la session ouverte par `POST /auth/login`. Le jeton de
         *     session est régénéré au passage : sans cela, un cookie obtenu avant le second facteur resterait
         *     valable après, ce qui est la fixation de session.
         *
         *     Il exige **les deux** : le cookie de session, qui dit de qui il s'agit, et le challenge rendu
         *     par la connexion, qui dit que le mot de passe vient d'être présenté il y a moins de cinq
         *     minutes. Aucun des deux ne dit ce que dit l'autre — sans le challenge, une session de premier
         *     facteur volée resterait élevable pendant douze heures par qui obtient un code.
         *
         *     Le challenge n'est consommé qu'en cas de **succès** : une faute de frappe ne doit pas obliger à
         *     refaire toute la connexion. Il compte en revanche ses échecs, et meurt au-delà d'un petit
         *     nombre — c'est ce qui borne la recherche exhaustive d'un code à six chiffres.
         *
         *     Aucun corps en retour : ce que la session ouvre désormais se lit sur `GET /auth/me`, qui reste
         *     le seul endroit d'où le client apprend ses droits.
         */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Réponse de la sonde de vivacité. */
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description Le premier facteur, tel que le formulaire de connexion l'envoie. */
        LoginRequest: {
            email: string;
            password: string;
        };
        /**
         * @description Le challenge de second facteur. C'est un objet en base et non un jeton signé : il doit être
         *     révocable à la seconde où il est consommé, ce qu'un jeton sans état ne permet pas. Le serveur
         *     n'en garde que l'empreinte — cette valeur n'est rendue qu'une fois.
         */
        MfaChallenge: {
            challenge: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Ce qu'une session vivante apprend au client. */
        Me: {
            operator: components["schemas"]["CurrentOperator"];
            permissions: string[];
            elevated: boolean;
            secondFactors: components["schemas"]["SecondFactors"];
            /** Format: date-time */
            absoluteExpiresAt: string;
        };
        /**
         * @description Ce que l'opérateur détient comme second facteur — jamais ce qu'il vaut. Un booléen et un
         *     compte ne se rejouent pas, là où le secret et les codes eux-mêmes ne sont montrés qu'une fois,
         *     à l'enrôlement.
         *
         *     C'est ce qui permet à l'écran de savoir s'il conduit à l'enrôlement ou au challenge, sans
         *     essayer l'un pour découvrir qu'il fallait l'autre. step-024 y ajoutera le compte de passkeys.
         */
        SecondFactors: {
            totp: boolean;
            recoveryCodesRemaining: number;
        };
        /**
         * @description Rendu **une seule fois**, à l'enrôlement. Aucune route ne le rend ensuite : le secret est
         *     chiffré au repos et les codes sont hachés, donc le serveur lui-même ne saurait plus les
         *     recomposer.
         */
        TotpEnrollment: {
            secret: string;
            otpauthUri: string;
            recoveryCodes: string[];
        };
        /**
         * @description Ce que le formulaire du second facteur envoie. Le challenge vient de la réponse à
         *     `POST /auth/login` ; le cookie de session, lui, voyage tout seul.
         */
        MfaVerification: {
            challenge: string;
            /** @enum {string} */
            method: "totp" | "recovery_code";
            code: string;
        };
        /**
         * @description De quoi nommer l'opérateur à l'écran, et rien de plus. Ni `password_hash`, ni
         *     `mfa_totp_secret`, ni les identifiants WebAuthn : le type de domaine du store ne traverse pas
         *     cette frontière (§1.11), et `additionalProperties: false` fait refuser tout champ qu'un
         *     serveur ajouterait par mégarde.
         */
        CurrentOperator: {
            id: string;
            email: string;
            displayName: string;
        };
        /**
         * @description La forme d'erreur unique du produit. `code` se grep dans les journaux et ne se traduit pas,
         *     `message` s'affiche à l'opérateur. Le champ `errors[]` que le §1.4 annonce arrive avec la
         *     première route qui relaie la passerelle (step-060).
         */
        Error: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le process répond. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Le premier facteur est franchi ; le second reste à fournir. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaChallenge"];
                };
            };
            /** @description La requête n'a pas la forme que la route attend. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Les identifiants ne conviennent pas. Le corps est le même que l'adresse soit inconnue,
             *     que le mot de passe soit faux ou que le compte soit désactivé.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Trop d'échecs sur ce compte ou depuis cette adresse. Le message porte la durée restante :
             *     un refus muet ferait retenter l'opérateur, puis ouvrir un ticket.
             */
            429: {
                headers: {
                    /**
                     * @description Secondes restant à attendre. Un entier et jamais une date HTTP : une date oblige le
                     *     client à faire confiance à sa propre horloge pour la soustraire.
                     */
                    "Retry-After": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Une session vit, et voici ce qu'elle ouvre. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /**
             * @description Aucune session vivante. Le corps est le même qu'il n'y ait pas de cookie, que son sceau
             *     ne colle pas, que la session soit échue, oisive, fermée, ou que le compte ait été
             *     désactivé : les distinguer dirait à qui teste un cookie ce qu'il vaut encore.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La session est fermée, qu'elle ait existé ou non. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enrollTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'authentificateur est enrôlé ; voici ce qui ne sera plus jamais montré. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnrollment"];
                };
            };
            /**
             * @description Aucune session vivante. Un enrôlement anonyme permettrait d'attacher un authentificateur à
             *     un compte qu'on ne détient pas.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Un second facteur est déjà en place et la session n'a pas franchi le sien. Le remplacer
             *     depuis une session de premier facteur reviendrait à le contourner : quiconque détient le
             *     mot de passe s'en enrôlerait un neuf.
             *
             *     Le refus dit ce qu'il faut faire — franchir le second facteur en cours, ou passer par un
             *     détenteur d'`operators:manage` s'il est perdu. Un contrôle qui refuse dit où s'arrête
             *     l'accès.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerification"];
            };
        };
        responses: {
            /** @description Le second facteur est vérifié ; la session est élevée. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La requête n'a pas la forme que la route attend. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Le second facteur n'a pas été accepté. Le corps est le même que le code soit faux, déjà
             *     servi, que le challenge soit inconnu, échu, consommé ou qu'il ait épuisé ses essais, ou
             *     qu'aucune session ne vive : les distinguer dirait à une machine où elle en est.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
