/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/[_]design'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ShellAlertesRouteImport } from './routes/_shell.alertes'
import { Route as ShellAntispamRouteImport } from './routes/_shell.antispam'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellClientsRouteImport } from './routes/_shell.clients'
import { Route as ShellComptesRouteImport } from './routes/_shell.comptes'
import { Route as ShellConnecteursRouteImport } from './routes/_shell.connecteurs'
import { Route as ShellDesabonnementsRouteImport } from './routes/_shell.desabonnements'
import { Route as ShellEntrantsRouteImport } from './routes/_shell.entrants'
import { Route as ShellFacturationRouteImport } from './routes/_shell.facturation'
import { Route as ShellGroupesRouteImport } from './routes/_shell.groupes'
import { Route as ShellOperateursRouteImport } from './routes/_shell.operateurs'
import { Route as ShellReecritureRouteImport } from './routes/_shell.reecriture'
import { Route as ShellRolesRouteImport } from './routes/_shell.roles'
import { Route as ShellRoutesRouteImport } from './routes/_shell.routes'
import { Route as ShellScriptsRouteImport } from './routes/_shell.scripts'
import { Route as ShellSessionsRouteImport } from './routes/_shell.sessions'
import { Route as ShellTraficRouteImport } from './routes/_shell.trafic'
import { Route as ConnexionIndexRouteImport } from './routes/connexion.index'
import { Route as ConnexionEnrolementRouteImport } from './routes/connexion.enrolement'
import { Route as ConnexionVerificationRouteImport } from './routes/connexion.verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/_design',
  path: '/_design',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAlertesRoute = ShellAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAntispamRoute = ShellAntispamRouteImport.update({
  id: '/antispam',
  path: '/antispam',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientsRoute = ShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComptesRoute = ShellComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnecteursRoute = ShellConnecteursRouteImport.update({
  id: '/connecteurs',
  path: '/connecteurs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDesabonnementsRoute = ShellDesabonnementsRouteImport.update({
  id: '/desabonnements',
  path: '/desabonnements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEntrantsRoute = ShellEntrantsRouteImport.update({
  id: '/entrants',
  path: '/entrants',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFacturationRoute = ShellFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGroupesRoute = ShellGroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperateursRoute = ShellOperateursRouteImport.update({
  id: '/operateurs',
  path: '/operateurs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReecritureRoute = ShellReecritureRouteImport.update({
  id: '/reecriture',
  path: '/reecriture',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRolesRoute = ShellRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRoutesRoute = ShellRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScriptsRoute = ShellScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsRoute = ShellSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTraficRoute = ShellTraficRouteImport.update({
  id: '/trafic',
  path: '/trafic',
  getParentRoute: () => ShellRoute,
} as any)
const ConnexionIndexRoute = ConnexionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnexionRoute,
} as any)
const ConnexionEnrolementRoute = ConnexionEnrolementRouteImport.update({
  id: '/enrolement',
  path: '/enrolement',
  getParentRoute: () => ConnexionRoute,
} as any)
const ConnexionVerificationRoute = ConnexionVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => ConnexionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_design': typeof DesignRoute
  '/connexion': typeof ConnexionRouteWithChildren
  '/alertes': typeof ShellAlertesRoute
  '/antispam': typeof ShellAntispamRoute
  '/audit': typeof ShellAuditRoute
  '/clients': typeof ShellClientsRoute
  '/comptes': typeof ShellComptesRoute
  '/connecteurs': typeof ShellConnecteursRoute
  '/desabonnements': typeof ShellDesabonnementsRoute
  '/entrants': typeof ShellEntrantsRoute
  '/facturation': typeof ShellFacturationRoute
  '/groupes': typeof ShellGroupesRoute
  '/operateurs': typeof ShellOperateursRoute
  '/reecriture': typeof ShellReecritureRoute
  '/roles': typeof ShellRolesRoute
  '/routes': typeof ShellRoutesRoute
  '/scripts': typeof ShellScriptsRoute
  '/sessions': typeof ShellSessionsRoute
  '/trafic': typeof ShellTraficRoute
  '/connexion/enrolement': typeof ConnexionEnrolementRoute
  '/connexion/verification': typeof ConnexionVerificationRoute
  '/connexion/': typeof ConnexionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/_design': typeof DesignRoute
  '/alertes': typeof ShellAlertesRoute
  '/antispam': typeof ShellAntispamRoute
  '/audit': typeof ShellAuditRoute
  '/clients': typeof ShellClientsRoute
  '/comptes': typeof ShellComptesRoute
  '/connecteurs': typeof ShellConnecteursRoute
  '/desabonnements': typeof ShellDesabonnementsRoute
  '/entrants': typeof ShellEntrantsRoute
  '/facturation': typeof ShellFacturationRoute
  '/groupes': typeof ShellGroupesRoute
  '/operateurs': typeof ShellOperateursRoute
  '/reecriture': typeof ShellReecritureRoute
  '/roles': typeof ShellRolesRoute
  '/routes': typeof ShellRoutesRoute
  '/scripts': typeof ShellScriptsRoute
  '/sessions': typeof ShellSessionsRoute
  '/trafic': typeof ShellTraficRoute
  '/connexion/enrolement': typeof ConnexionEnrolementRoute
  '/connexion/verification': typeof ConnexionVerificationRoute
  '/connexion': typeof ConnexionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_design': typeof DesignRoute
  '/_shell': typeof ShellRouteWithChildren
  '/connexion': typeof ConnexionRouteWithChildren
  '/_shell/alertes': typeof ShellAlertesRoute
  '/_shell/antispam': typeof ShellAntispamRoute
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/clients': typeof ShellClientsRoute
  '/_shell/comptes': typeof ShellComptesRoute
  '/_shell/connecteurs': typeof ShellConnecteursRoute
  '/_shell/desabonnements': typeof ShellDesabonnementsRoute
  '/_shell/entrants': typeof ShellEntrantsRoute
  '/_shell/facturation': typeof ShellFacturationRoute
  '/_shell/groupes': typeof ShellGroupesRoute
  '/_shell/operateurs': typeof ShellOperateursRoute
  '/_shell/reecriture': typeof ShellReecritureRoute
  '/_shell/roles': typeof ShellRolesRoute
  '/_shell/routes': typeof ShellRoutesRoute
  '/_shell/scripts': typeof ShellScriptsRoute
  '/_shell/sessions': typeof ShellSessionsRoute
  '/_shell/trafic': typeof ShellTraficRoute
  '/connexion/enrolement': typeof ConnexionEnrolementRoute
  '/connexion/verification': typeof ConnexionVerificationRoute
  '/connexion/': typeof ConnexionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_design'
    | '/connexion'
    | '/alertes'
    | '/antispam'
    | '/audit'
    | '/clients'
    | '/comptes'
    | '/connecteurs'
    | '/desabonnements'
    | '/entrants'
    | '/facturation'
    | '/groupes'
    | '/operateurs'
    | '/reecriture'
    | '/roles'
    | '/routes'
    | '/scripts'
    | '/sessions'
    | '/trafic'
    | '/connexion/enrolement'
    | '/connexion/verification'
    | '/connexion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/_design'
    | '/alertes'
    | '/antispam'
    | '/audit'
    | '/clients'
    | '/comptes'
    | '/connecteurs'
    | '/desabonnements'
    | '/entrants'
    | '/facturation'
    | '/groupes'
    | '/operateurs'
    | '/reecriture'
    | '/roles'
    | '/routes'
    | '/scripts'
    | '/sessions'
    | '/trafic'
    | '/connexion/enrolement'
    | '/connexion/verification'
    | '/connexion'
  id:
    | '__root__'
    | '/'
    | '/_design'
    | '/_shell'
    | '/connexion'
    | '/_shell/alertes'
    | '/_shell/antispam'
    | '/_shell/audit'
    | '/_shell/clients'
    | '/_shell/comptes'
    | '/_shell/connecteurs'
    | '/_shell/desabonnements'
    | '/_shell/entrants'
    | '/_shell/facturation'
    | '/_shell/groupes'
    | '/_shell/operateurs'
    | '/_shell/reecriture'
    | '/_shell/roles'
    | '/_shell/routes'
    | '/_shell/scripts'
    | '/_shell/sessions'
    | '/_shell/trafic'
    | '/connexion/enrolement'
    | '/connexion/verification'
    | '/connexion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  ShellRoute: typeof ShellRouteWithChildren
  ConnexionRoute: typeof ConnexionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_design': {
      id: '/_design'
      path: '/_design'
      fullPath: '/_design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/alertes': {
      id: '/_shell/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof ShellAlertesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/antispam': {
      id: '/_shell/antispam'
      path: '/antispam'
      fullPath: '/antispam'
      preLoaderRoute: typeof ShellAntispamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clients': {
      id: '/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ShellClientsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comptes': {
      id: '/_shell/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ShellComptesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connecteurs': {
      id: '/_shell/connecteurs'
      path: '/connecteurs'
      fullPath: '/connecteurs'
      preLoaderRoute: typeof ShellConnecteursRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/desabonnements': {
      id: '/_shell/desabonnements'
      path: '/desabonnements'
      fullPath: '/desabonnements'
      preLoaderRoute: typeof ShellDesabonnementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/entrants': {
      id: '/_shell/entrants'
      path: '/entrants'
      fullPath: '/entrants'
      preLoaderRoute: typeof ShellEntrantsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/facturation': {
      id: '/_shell/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof ShellFacturationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/groupes': {
      id: '/_shell/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof ShellGroupesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operateurs': {
      id: '/_shell/operateurs'
      path: '/operateurs'
      fullPath: '/operateurs'
      preLoaderRoute: typeof ShellOperateursRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reecriture': {
      id: '/_shell/reecriture'
      path: '/reecriture'
      fullPath: '/reecriture'
      preLoaderRoute: typeof ShellReecritureRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roles': {
      id: '/_shell/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ShellRolesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/routes': {
      id: '/_shell/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof ShellRoutesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scripts': {
      id: '/_shell/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ShellScriptsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions': {
      id: '/_shell/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ShellSessionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trafic': {
      id: '/_shell/trafic'
      path: '/trafic'
      fullPath: '/trafic'
      preLoaderRoute: typeof ShellTraficRouteImport
      parentRoute: typeof ShellRoute
    }
    '/connexion/': {
      id: '/connexion/'
      path: '/'
      fullPath: '/connexion/'
      preLoaderRoute: typeof ConnexionIndexRouteImport
      parentRoute: typeof ConnexionRoute
    }
    '/connexion/enrolement': {
      id: '/connexion/enrolement'
      path: '/enrolement'
      fullPath: '/connexion/enrolement'
      preLoaderRoute: typeof ConnexionEnrolementRouteImport
      parentRoute: typeof ConnexionRoute
    }
    '/connexion/verification': {
      id: '/connexion/verification'
      path: '/verification'
      fullPath: '/connexion/verification'
      preLoaderRoute: typeof ConnexionVerificationRouteImport
      parentRoute: typeof ConnexionRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAlertesRoute: typeof ShellAlertesRoute
  ShellAntispamRoute: typeof ShellAntispamRoute
  ShellAuditRoute: typeof ShellAuditRoute
  ShellClientsRoute: typeof ShellClientsRoute
  ShellComptesRoute: typeof ShellComptesRoute
  ShellConnecteursRoute: typeof ShellConnecteursRoute
  ShellDesabonnementsRoute: typeof ShellDesabonnementsRoute
  ShellEntrantsRoute: typeof ShellEntrantsRoute
  ShellFacturationRoute: typeof ShellFacturationRoute
  ShellGroupesRoute: typeof ShellGroupesRoute
  ShellOperateursRoute: typeof ShellOperateursRoute
  ShellReecritureRoute: typeof ShellReecritureRoute
  ShellRolesRoute: typeof ShellRolesRoute
  ShellRoutesRoute: typeof ShellRoutesRoute
  ShellScriptsRoute: typeof ShellScriptsRoute
  ShellSessionsRoute: typeof ShellSessionsRoute
  ShellTraficRoute: typeof ShellTraficRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAlertesRoute: ShellAlertesRoute,
  ShellAntispamRoute: ShellAntispamRoute,
  ShellAuditRoute: ShellAuditRoute,
  ShellClientsRoute: ShellClientsRoute,
  ShellComptesRoute: ShellComptesRoute,
  ShellConnecteursRoute: ShellConnecteursRoute,
  ShellDesabonnementsRoute: ShellDesabonnementsRoute,
  ShellEntrantsRoute: ShellEntrantsRoute,
  ShellFacturationRoute: ShellFacturationRoute,
  ShellGroupesRoute: ShellGroupesRoute,
  ShellOperateursRoute: ShellOperateursRoute,
  ShellReecritureRoute: ShellReecritureRoute,
  ShellRolesRoute: ShellRolesRoute,
  ShellRoutesRoute: ShellRoutesRoute,
  ShellScriptsRoute: ShellScriptsRoute,
  ShellSessionsRoute: ShellSessionsRoute,
  ShellTraficRoute: ShellTraficRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ConnexionRouteChildren {
  ConnexionEnrolementRoute: typeof ConnexionEnrolementRoute
  ConnexionVerificationRoute: typeof ConnexionVerificationRoute
  ConnexionIndexRoute: typeof ConnexionIndexRoute
}

const ConnexionRouteChildren: ConnexionRouteChildren = {
  ConnexionEnrolementRoute: ConnexionEnrolementRoute,
  ConnexionVerificationRoute: ConnexionVerificationRoute,
  ConnexionIndexRoute: ConnexionIndexRoute,
}

const ConnexionRouteWithChildren = ConnexionRoute._addFileChildren(
  ConnexionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  ShellRoute: ShellRouteWithChildren,
  ConnexionRoute: ConnexionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
